version: '3.8'

services:
  postgresql:
    build:
      context: ./database-postgresql
      dockerfile: Dockerfile
    container_name: currency-track-postgresql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - currency-track-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=currency_track

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: currency-track-dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - currency-track-network

volumes:
  grafana_storage: {}
  pgdata: {}

networks:
  currency-track-network: {}